// import { COLORS } from "../constants";

export const products = [
  {
    id: 1,
    title: "Dove silky",
    description: "Shoe in Miniacs Shop",
    category: "Cream",
    date: "Dec 24",
    image: require("../assets/images/walkthrough/cream2.jpg"),
    price: 500,
  },

  {
    id: 7,
    title: "Both women`s and men`s show",
    category: "Show",
    description: "Stay tune and check your notif everyday",
    date: "6 hours",
    image: require("../assets/images/walkthrough/shoe3.png"),
    price: 700,
  },
  {
    id: 4,
    title: "Beauty womens bag",
    category: "Bag",
    description: "Stay tune and check your notif everyday",
    date: "6 hours",
    image: require("../assets/images/walkthrough/bag2.png"),
    price: 1000,
  },
  {
    id: 2,
    title: "Dove nourishing body cream",
    category: "Cream",
    description: "Stay tune and check your notif everyday",
    date: "6 hours",
    image: require("../assets/images/walkthrough/cream4.2.jpg"),
    price: 800,
  },
  {
    id: 5,
    category: "Bag",
    title: "Awesome womens hand bag",
    description: "Stay tune and check your notif everyday",
    date: "6 hours",
    image: require("../assets/images/walkthrough/bag3.png"),
    price: 1500,
  },
  {
    id: 6,
    category: "Shoe",
    title: "Nice women show ",
    description: "Stay tune and check your notif everyday",
    date: "6 hours",
    image: require("../assets/images/walkthrough/shoe1.png"),
    price: 500,
  },
  {
    id: 3,
    title: "Sensitive Skin bodylotion",
    description: "Stay tune and check your notif everyday",
    category: "Cream",
    date: "6 hours",
    image: require("../assets/images/walkthrough/cream4.1.jpg"),
    price: 400,
  },

  {
    id: 8,
    title: "Men`s awesome show",
    category: "Shoe",
    description: "Stay tune and check your notif everyday",
    date: "6 hours",
    image: require("../assets/images/walkthrough/shoem.png"),
    price: 700,
  },
];
